// scripts/generate-blur.mjs
// Regenerates src/data/blur.ts: a tiny base64 preview for every photograph in
// public/images plus every video poster in public/video. CinematicImage picks
// these up automatically, so run this after adding or re-encoding any image:
//   node scripts/generate-blur.mjs
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const targets = [
  ...readdirSync("public/images")
    .filter((f) => /\.jpe?g$/i.test(f))
    .map((f) => ({ file: path.join("public/images", f), url: `/images/${f}` })),
  ...readdirSync("public/video")
    .filter((f) => /\.jpe?g$/i.test(f))
    .map((f) => ({ file: path.join("public/video", f), url: `/video/${f}` })),
];

const entries = [];
for (const t of targets) {
  const buf = await sharp(t.file)
    .resize(14, 14, { fit: "inside" })
    .webp({ quality: 30 })
    .toBuffer();
  entries.push([t.url, `data:image/webp;base64,${buf.toString("base64")}`]);
}
entries.sort((a, b) => a[0].localeCompare(b[0]));

const body = entries.map(([k, v]) => `  "${k}":\n    "${v}",`).join("\n");
const out = `// src/data/blur.ts
// GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Tiny base64 previews keyed by public URL; CinematicImage applies them as
// next/image blur placeholders automatically.
export const blurMap: Record<string, string> = {
${body}
};
`;
writeFileSync("src/data/blur.ts", out);
console.log(`blur.ts written: ${entries.length} entries, ${Math.round(out.length / 1024)}KB`);
