// scripts/generate-blur.mjs
// Regenerates src/data/blur.ts: a tiny base64 preview for every photograph in
// public/images plus every video poster in public/video. Photo (and the fold)
// pick these up automatically, so run this after adding or re-encoding any
// image:
//   npm run blur
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

// Resolved from this file, so the script reads and writes the same place
// from any cwd.
const ROOT = path.resolve(import.meta.dirname, "..");
const dir = (rel) => path.join(ROOT, rel);

const targets = [
  ...readdirSync(dir("public/images"))
    .filter((f) => /\.jpe?g$/i.test(f))
    .map((f) => ({ file: dir(path.join("public/images", f)), url: `/images/${f}` })),
  ...readdirSync(dir("public/video"))
    .filter((f) => /\.jpe?g$/i.test(f))
    .map((f) => ({ file: dir(path.join("public/video", f)), url: `/video/${f}` })),
];

const entries = [];
for (const t of targets) {
  const buf = await sharp(t.file)
    .resize(14, 14, { fit: "inside" })
    .webp({ quality: 30 })
    .toBuffer();
  entries.push([t.url, `data:image/webp;base64,${buf.toString("base64")}`]);
}
entries.sort((a, b) => a[0].localeCompare(b[0]));

const body = entries.map(([k, v]) => `  "${k}":\n    "${v}",`).join("\n");
const out = `// src/data/blur.ts
// GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Tiny base64 previews keyed by public URL; Photo applies them as next/image
// blur placeholders automatically.
export const blurMap: Record<string, string> = {
${body}
};
`;
writeFileSync(dir("src/data/blur.ts"), out);
console.log(`blur.ts written: ${entries.length} entries, ${Math.round(out.length / 1024)}KB`);
