// src/design/tokens.ts
// THE source of truth for the "Painel de LED" design system. Everything else
// is derived from here:
//   - src/app/tokens.css     generated by scripts/generate-tokens.mjs
//   - src/components/pdf/theme.ts   reads the same values, converted to hex
//   - src/design/__tests__/contrast.test.ts   proves the pairs clear WCAG AA
//
// This file must stay plain, erasable TypeScript with no imports: the
// generator loads it directly in Node (type stripping), and Tailwind gets the
// CSS it renders.
//
// Palette story. The band's stage backdrop is a wall of blue LED dots behind a
// red acrylic wordmark. So: a night-blue ground (the panel switched off), one
// LED blue that carries the interface, one red reserved for the wordmark and
// the primary CTA, white/grey ink, and a sepia set for the 1969 chapter.

export const tokens = {
  palette: {
    // Night — the panel with the power off. Blue-biased near-black.
    'night-950': 'oklch(12% 0.028 262)',
    'night-900': 'oklch(16.5% 0.03 262)',
    'night-800': 'oklch(21% 0.032 262)',
    'night-700': 'oklch(28% 0.034 262)',
    // LED — the lit dot. 500 is the accent; 300 is the only blue allowed as
    // small text on the dark surfaces; 700 is the blue for the paper theme;
    // 900 is an unlit dot.
    'led-200': 'oklch(90% 0.06 232)',
    'led-300': 'oklch(83% 0.1 236)',
    'led-500': 'oklch(70% 0.16 240)',
    'led-700': 'oklch(50% 0.16 250)',
    'led-900': 'oklch(30% 0.075 254)',
    // Acrylic red — sampled from the backdrop. Wordmark and primary CTA only.
    'red-500': '#ee3524',
    'red-400': '#ff5240',
    // Ink — the greys for type.
    'ink-50': 'oklch(97% 0.005 250)',
    'ink-300': 'oklch(76% 0.02 250)',
    'ink-500': 'oklch(63% 0.02 252)',
    // Paper — the internal editor and both PDFs.
    'paper-50': 'oklch(98.5% 0.004 250)',
    'paper-100': 'oklch(95.5% 0.006 250)',
    'paper-200': 'oklch(89% 0.01 250)',
    'paper-600': 'oklch(45% 0.025 255)',
    'paper-900': 'oklch(20% 0.03 262)',
    // Sepia — the 1969 chapter. Warm, low chroma, the founders' photograph.
    'sepia-950': 'oklch(15% 0.022 62)',
    'sepia-900': 'oklch(20% 0.028 64)',
    'sepia-800': 'oklch(26% 0.032 66)',
    'sepia-300': 'oklch(80% 0.05 78)',
    'sepia-100': 'oklch(94% 0.03 82)',
  },

  font: {
    // --font-outfit is set on <html> by next/font in layout.tsx.
    sans: "var(--font-outfit), 'Outfit', ui-sans-serif, system-ui, sans-serif",
  },

  // Fluid type scale. One family; size, weight and tracking do the work.
  text: {
    '2xs': 'clamp(0.66rem, 0.62rem + 0.15vi, 0.74rem)',
    xs: 'clamp(0.72rem, 0.68rem + 0.2vi, 0.82rem)',
    sm: 'clamp(0.82rem, 0.78rem + 0.2vi, 0.95rem)',
    base: 'clamp(0.98rem, 0.92rem + 0.25vi, 1.12rem)',
    lg: 'clamp(1.12rem, 1.04rem + 0.4vi, 1.4rem)',
    xl: 'clamp(1.3rem, 1.2rem + 0.7vi, 1.75rem)',
    '2xl': 'clamp(1.6rem, 1.4rem + 1.1vi, 2.3rem)',
    '3xl': 'clamp(2rem, 1.5rem + 2.2vi, 3.2rem)',
    '4xl': 'clamp(2.5rem, 1.6rem + 3.8vi, 4.4rem)',
    '5xl': 'clamp(3rem, 1.6rem + 5.6vi, 6rem)',
    '6xl': 'clamp(3.6rem, 1.6rem + 8vi, 8.5rem)',
  },

  tracking: {
    label: '0.18em',
    wide: '0.08em',
    tight: '-0.02em',
    display: '-0.035em',
  },

  // Two curves, two purposes. "light" is how a LED comes on: fast attack, long
  // settle. "slide" is how a panel of content moves: symmetric, deliberate.
  ease: {
    light: 'cubic-bezier(0.16, 1, 0.3, 1)',
    slide: 'cubic-bezier(0.7, 0, 0.2, 1)',
  },

  dur: {
    quick: '180ms',
    slide: '480ms',
    light: '900ms',
  },

  radius: {
    sm: '2px',
    pill: '999px',
  },

  layout: {
    // --container-* is a Tailwind namespace: this becomes `max-w-site`.
    'container-site': '88rem',
    'pad-inline': 'clamp(1.25rem, 4vw, 3.5rem)',
    'section-gap': 'clamp(4.5rem, 10vw, 9rem)',
    'dot-pitch': '6px',
  },
} as const;

export type PaletteName = keyof typeof tokens.palette;

/** A semantic value: a palette name or a literal colour. */
type SemanticValue = PaletteName | `#${string}` | `oklch(${string})` | `rgb(${string})`;

interface SemanticMap {
  surface: SemanticValue;
  'surface-raise': SemanticValue;
  'surface-high': SemanticValue;
  line: SemanticValue;
  'line-strong': SemanticValue;
  ink: SemanticValue;
  'ink-muted': SemanticValue;
  'ink-low': SemanticValue;
  led: SemanticValue;
  'led-text': SemanticValue;
  'led-dim': SemanticValue;
  red: SemanticValue;
  'red-hot': SemanticValue;
  'on-red': SemanticValue;
}

// Semantic layers. `dark` is the site; `paper` is the editor and the PDFs;
// `sepia` is scoped to the 1969 chapter of /historia.
export const themes: Record<'dark' | 'paper' | 'sepia', SemanticMap> = {
  dark: {
    surface: 'night-950',
    'surface-raise': 'night-900',
    'surface-high': 'night-800',
    line: 'oklch(100% 0 0 / 0.1)',
    'line-strong': 'oklch(100% 0 0 / 0.42)',
    ink: 'ink-50',
    'ink-muted': 'ink-300',
    'ink-low': 'ink-500',
    led: 'led-500',
    'led-text': 'led-300',
    'led-dim': 'led-900',
    red: 'red-500',
    'red-hot': 'red-400',
    'on-red': 'night-950',
  },
  paper: {
    surface: 'paper-50',
    'surface-raise': 'paper-100',
    'surface-high': '#ffffff',
    line: 'oklch(20% 0.03 262 / 0.12)',
    'line-strong': 'oklch(20% 0.03 262 / 0.58)',
    ink: 'paper-900',
    'ink-muted': 'paper-600',
    'ink-low': 'paper-600',
    led: 'led-700',
    'led-text': 'led-700',
    'led-dim': 'paper-200',
    red: 'red-500',
    'red-hot': 'red-400',
    'on-red': 'night-950',
  },
  sepia: {
    surface: 'sepia-950',
    'surface-raise': 'sepia-900',
    'surface-high': 'sepia-800',
    line: 'oklch(94% 0.03 82 / 0.12)',
    'line-strong': 'oklch(94% 0.03 82 / 0.45)',
    ink: 'sepia-100',
    'ink-muted': 'sepia-300',
    'ink-low': 'sepia-300',
    led: 'led-500',
    'led-text': 'led-300',
    'led-dim': 'sepia-800',
    red: 'red-500',
    'red-hot': 'red-400',
    'on-red': 'night-950',
  },
};

/** Resolves a semantic name to its literal colour string in a theme. */
export function resolveColor(name: string, theme: keyof typeof themes = 'dark'): string {
  const map: Record<string, string> = { ...themes[theme] };
  const value = map[name] ?? name;
  const palette = tokens.palette as Record<string, string>;
  return palette[value] ?? value;
}

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((l) => `  ${l}`).join('\n')}\n}\n`;
}

/**
 * Renders src/app/tokens.css. Palette and semantic aliases go inside @theme so
 * Tailwind emits utilities (bg-surface, text-led-text, ease-light…); the paper
 * and sepia layers re-point the semantic variables on a scope.
 */
export function renderTokensCss(): string {
  const theme: string[] = [];
  theme.push('/* palette */');
  for (const [k, v] of Object.entries(tokens.palette)) theme.push(`--color-${k}: ${v};`);
  theme.push('', '/* semantic (dark) */');
  for (const [k, v] of Object.entries(themes.dark)) {
    const ref = v in tokens.palette ? `var(--color-${v})` : v;
    theme.push(`--color-${k}: ${ref};`);
  }
  theme.push('', '/* type */');
  for (const [k, v] of Object.entries(tokens.font)) theme.push(`--font-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.text)) theme.push(`--text-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.tracking)) theme.push(`--tracking-${k}: ${v};`);
  theme.push('', '/* motion */');
  for (const [k, v] of Object.entries(tokens.ease)) theme.push(`--ease-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.dur)) theme.push(`--dur-${k}: ${v};`);
  theme.push('', '/* shape & layout */');
  for (const [k, v] of Object.entries(tokens.radius)) theme.push(`--radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.layout)) theme.push(`--${k}: ${v};`);

  const scoped = (name: 'paper' | 'sepia', scheme: 'light' | 'dark') => {
    const lines: string[] = [];
    for (const [k, v] of Object.entries(themes[name])) {
      const ref = v in tokens.palette ? `var(--color-${v})` : v;
      lines.push(`--color-${k}: ${ref};`);
    }
    lines.push(`color-scheme: ${scheme};`);
    return block(`[data-theme='${name}']`, lines);
  };

  return [
    '/* src/app/tokens.css',
    '   GENERATED by scripts/generate-tokens.mjs from src/design/tokens.ts.',
    '   Do not edit by hand: change tokens.ts and run `npm run tokens`. */',
    '',
    block('@theme', theme),
    scoped('paper', 'light'),
    scoped('sepia', 'dark'),
  ].join('\n');
}
